# Use a Node.js image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy the rest of the frontend source code
COPY frontend /app

# Expose the development server port
EXPOSE 5174

# Default command to run the development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
