# Use a lightweight Go image
FROM golang:1.20

# Set the working directory
WORKDIR /app

# Copy Go modules and source code
COPY backend/go.mod backend/go.sum ./
RUN go mod download
COPY backend /app/backend

# Set environment variables
ENV CGO_ENABLED=0 GOOS=linux

# Build the Go application
RUN go build -o main backend/cmd/main.go

# Expose the backend port
EXPOSE 8080

# Command to run the backend server
CMD ["./main"]
